version: '3.9'
services:

  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    restart: unless-stopped
    volumes:
    - grafana-data:/var/lib/grafana
    ports:
    - 3000:3000
    networks: 
    - platform_science_code_exercise

  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    restart: unless-stopped
    volumes:
    - ./loki-config.yml:/mnt/config/loki-config.yml
    - loki-data:/loki
    ports:
    - 3100:3100
    networks: 
    - platform_science_code_exercise
    command: 
    - '-config.file=/mnt/config/loki-config.yml'

  promtail:
    image: grafana/promtail:2.3.0
    container_name: promtail
    restart: unless-stopped
    networks: 
    - platform_science_code_exercise
    volumes:
    - data_logs:/logs:ro
    - /home/:/home_server:ro
    - /root/:/root_user:ro
    - ./promtail.yml:/etc/promtail/promtail.yml
    - promtail-data:/tmp
    command: -config.file=/etc/promtail/promtail.yml
  
  prometheus:
    image: prom/prometheus:v2.30.0
    container_name: master_prometheus
    restart: unless-stopped
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus
    ports:
    - 9090:9090
    networks: 
    - platform_science_code_exercise
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=90d'
    - '--storage.tsdb.retention.size=100GB'
    - '--web.enable-lifecycle'

networks:
  platform_science_code_exercise:
    name: net-net_platform_science_code_exercise-demo

volumes:
  grafana-data:
  loki-data:
  promtail-data:
  prometheus-data: 
  data_logs: