version: '3.9'

services:
  k6:
    build: 
      context: .
    image: loadimpact/k6
    command: run /test.js
    volumes:
      - ./test.js:/test.js
      - ./k6config.js:/k6config.js
    networks: 
      - platform_science_code_exercise
    

networks:
  platform_science_code_exercise:
    name: net_platform_science_code_exercise