version: '3.9'

services:

  platform_science_code_exercise_backend:
    restart: always
    container_name: platform_science_code_exercise_container
    build: .
    ports:
      - 2001:2001
    volumes:
      - .:/app
    networks: 
      - platform_science_code_exercise
    

networks:
  platform_science_code_exercise:
    name: net_platform_science_code_exercise