version: '3.9'

services:

  file_server_backend:
    restart: always
    container_name: file_server_container
    build: .
    ports:
      - 1001:1001
    volumes:
      - .:/app
    networks: 
      - platform_science_code_exercise
    

networks:
  platform_science_code_exercise:
    name: net_platform_science_code_exercise