version: '3'

services:

  app:
    build: .
    ports:
      - "3001:3000"
    networks: 
      - platform_science_code_exercise

networks:
  platform_science_code_exercise:
    name: net_platform_science_code_exercise